### ISSUE TITLE
CSRRC Trapping on HPMCOUNTER

### ISSUE THREAD

**Issue by marnovandermaas** [CTSRD-CHERI/RVBS#1]
This instruction traps in RVBS and not in Spike:
```
.4byte 0xc16031f3 # csrrc r3, hpmcounter22 (0xc16), r0
```

The rvbs log says that CSR 0xc16 is not implemented:
```
CSR 0xc16 unimplemented - CSRReq { idx: 'hc16, val: 'h0000000000000000, rType: RC, rEffects: NOWRITE }
time 1485110 -- pc: 0x80000000 -- csrrc	x3(gp), x0(zero), 0xc16  	--	rs1 (0x0) into unknown
time 1485120 -- >>> TRAP <<< -- mcause <= IllegalInst (exception 2), mepc <= 0x80000000, mtval <= 0x0, pc <= 0x0, pcc <= Valid: 0x1 Perms: 0x78fff Kind: UNSEALED Addr: 0x0 Base: 0x0 Length: 0x1ffffffffffffffff
```

**Comment by marnovandermaas** [comment]
Another unimplemented CSR: pmpaddr4 (0x3b4)

**Comment by gameboo** [comment]
The hpm counters are indeed not implemented so a trap is the expected behavior here. On the pmpaddr one, I believe they should show up if you build with pmp support, that is setting `PMP=1` when running `make`...
Let me know if that works for you.
